SECOND COMMIT	

apps:
- name: websocket.invitigo.com/
  cwd: /home/invitigocom/websocket.invitigo.com/
  script: "server.js"
  interpreter: "/usr/bin/node"
  env:
   NODE_ENV: "production"
   NODE_PORT: 3113

